"""Korean translations for yfinance sector and industry strings."""
from __future__ import annotations

SECTOR_KO: dict[str, str] = {
    "Technology": "기술",
    "Healthcare": "헬스케어",
    "Financial Services": "금융",
    "Consumer Cyclical": "경기소비재",
    "Communication Services": "커뮤니케이션",
    "Industrials": "산업재",
    "Consumer Defensive": "필수소비재",
    "Energy": "에너지",
    "Basic Materials": "기초소재",
    "Real Estate": "부동산",
    "Utilities": "유틸리티",
}

INDUSTRY_KO: dict[str, str] = {
    # Technology
    "Semiconductors": "반도체",
    "Semiconductor Equipment & Materials": "반도체 장비/소재",
    "Software - Infrastructure": "소프트웨어(인프라)",
    "Software - Application": "소프트웨어(응용)",
    "Information Technology Services": "IT 서비스",
    "Computer Hardware": "컴퓨터 하드웨어",
    "Consumer Electronics": "가전/전자기기",
    "Electronic Components": "전자 부품",
    "Electronic Gaming & Multimedia": "전자게임/멀티미디어",
    "Scientific & Technical Instruments": "과학/기술 기기",
    "Solar": "태양광",
    # Communication Services
    "Internet Content & Information": "인터넷 콘텐츠",
    "Internet Retail": "인터넷 소매",
    "Telecom Services": "통신 서비스",
    "Entertainment": "엔터테인먼트",
    "Media - Diversified": "미디어(종합)",
    "Publishing": "출판",
    "Broadcasting": "방송",
    "Advertising Agencies": "광고대행사",
    # Financial Services
    "Banks - Diversified": "은행(종합)",
    "Banks - Regional": "은행(지역)",
    "Credit Services": "신용/결제",
    "Insurance - Diversified": "보험(종합)",
    "Insurance - Life": "보험(생명)",
    "Insurance - Property & Casualty": "보험(손해)",
    "Insurance - Specialty": "보험(특수)",
    "Insurance - Reinsurance": "보험(재보험)",
    "Asset Management": "자산운용",
    "Capital Markets": "자본시장",
    "Financial Data & Stock Exchanges": "금융데이터/거래소",
    "Mortgage Finance": "모기지금융",
    "Specialty Finance": "특수금융",
    # Healthcare
    "Drug Manufacturers - General": "제약(종합)",
    "Drug Manufacturers - Specialty & Generic": "제약(특수/제네릭)",
    "Biotechnology": "바이오테크",
    "Medical Devices": "의료기기",
    "Medical Instruments & Supplies": "의료기기/소모품",
    "Diagnostics & Research": "진단/연구",
    "Healthcare Plans": "의료보험",
    "Health Information Services": "의료정보 서비스",
    "Medical Care Facilities": "의료시설",
    "Pharmaceutical Retailers": "약국/의약품 소매",
    # Consumer Cyclical
    "Auto Manufacturers": "자동차 제조",
    "Auto Parts": "자동차 부품",
    "Auto & Truck Dealerships": "자동차 딜러십",
    "Specialty Retail": "전문 소매",
    "Department Stores": "백화점",
    "Apparel Retail": "의류 소매",
    "Apparel Manufacturing": "의류 제조",
    "Footwear & Accessories": "신발/액세서리",
    "Home Improvement Retail": "홈인테리어 소매",
    "Furnishings, Fixtures & Appliances": "가구/가전",
    "Restaurants": "외식",
    "Resorts & Casinos": "리조트/카지노",
    "Lodging": "숙박",
    "Travel Services": "여행 서비스",
    "Leisure": "여가",
    "Personal Services": "개인 서비스",
    # Consumer Defensive
    "Beverages - Non-Alcoholic": "음료(비알코올)",
    "Beverages - Alcoholic": "음료(알코올)",
    "Beverages - Brewers": "음료(맥주)",
    "Beverages - Wineries & Distilleries": "음료(와인/증류주)",
    "Confectioners": "제과",
    "Packaged Foods": "포장식품",
    "Grocery Stores": "식료품점",
    "Discount Stores": "할인점",
    "Food Distribution": "식품 유통",
    "Tobacco": "담배",
    "Household & Personal Products": "가정/개인용품",
    "Education & Training Services": "교육/훈련 서비스",
    # Industrials
    "Aerospace & Defense": "항공우주/방위",
    "Airlines": "항공사",
    "Railroads": "철도",
    "Trucking": "트럭 운송",
    "Marine Shipping": "해운",
    "Integrated Freight & Logistics": "종합 물류",
    "Air Freight & Logistics": "항공 물류",
    "Waste Management": "폐기물 관리",
    "Engineering & Construction": "엔지니어링/건설",
    "Industrial Distribution": "산업재 유통",
    "Farm & Heavy Construction Machinery": "농기계/중장비",
    "Specialty Industrial Machinery": "특수 산업기계",
    "Tools & Accessories": "공구/부품",
    "Security & Protection Services": "보안/방호 서비스",
    "Staffing & Employment Services": "인력/고용 서비스",
    "Business Equipment & Supplies": "사무기기/용품",
    "Conglomerates": "복합기업",
    "Electrical Equipment & Parts": "전기장비/부품",
    # Energy
    "Oil & Gas Integrated": "석유/가스(통합)",
    "Oil & Gas Upstream": "석유/가스(상류)",
    "Oil & Gas Midstream": "석유/가스(중류)",
    "Oil & Gas Downstream": "석유/가스(하류)",
    "Oil & Gas Equipment & Services": "석유/가스 장비/서비스",
    "Oil & Gas Refining & Marketing": "석유/가스(정제/판매)",
    "Thermal Coal": "석탄(열탄)",
    "Uranium": "우라늄",
    # Basic Materials
    "Specialty Chemicals": "특수 화학",
    "Agricultural Inputs": "농업 투입재",
    "Chemicals": "화학",
    "Gold": "금",
    "Silver": "은",
    "Copper": "구리",
    "Steel": "철강",
    "Aluminum": "알루미늄",
    "Other Industrial Metals & Mining": "기타 산업금속/광업",
    "Lumber & Wood Production": "목재",
    "Paper & Paper Products": "제지",
    "Building Materials": "건축자재",
    # Real Estate
    "REIT - Residential": "리츠(주거)",
    "REIT - Retail": "리츠(소매)",
    "REIT - Office": "리츠(오피스)",
    "REIT - Industrial": "리츠(산업)",
    "REIT - Healthcare Facilities": "리츠(의료시설)",
    "REIT - Hotel & Motel": "리츠(호텔)",
    "REIT - Specialty": "리츠(특수)",
    "REIT - Diversified": "리츠(복합)",
    "REIT - Mortgage": "리츠(모기지)",
    "Real Estate Services": "부동산 서비스",
    "Real Estate - Development": "부동산 개발",
    "Real Estate - Diversified": "부동산(복합)",
    # Utilities
    "Utilities - Regulated Electric": "전기(규제)",
    "Utilities - Regulated Gas": "가스(규제)",
    "Utilities - Regulated Water": "수도(규제)",
    "Utilities - Independent Power Producers": "독립발전사업자",
    "Utilities - Renewable": "재생에너지 유틸리티",
    "Utilities - Diversified": "유틸리티(복합)",
}


def translate_sector(en: str | None) -> str:
    if not en:
        return "-"
    return SECTOR_KO.get(en, en)  # fallback to English if not mapped


def translate_industry(en: str | None) -> str:
    if not en:
        return "-"
    return INDUSTRY_KO.get(en, en)  # fallback to English if not mapped
